name: Deploy to Server

on:
  push:
    branches: 'master'
  workflow_dispatch:

jobs:
  build_site:
    runs-on: self-hosted
    steps:
      - name: Install yarn
        run: volta install yarn@latest
      - name: Pull repo
        run: cd /var/www/pws; git pull
      - name: Install dependencies
        run: yarn
      - name: Build website
        run: yarn build
      - name: Select Screen
        run: screen -x pws
      - name: Restart nodemon
        run: rs
